{% set name = "AstroGlue" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astroglue-{{ version }}.tar.gz
  sha256: ad15c3810f0617926aab7f685b6772b389c6eed74a2aca365f7bceddc09e6647

build:
  entry_points:
    - AstroGlue = AstroGlue.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - numpy <2.0.0
    - pandas
    - pyqt
    - glueviz ==1.2.0
    - glue-qt ==0.3.1
    - glue-vispy-viewers ==1.1.0
    - astrolink

test:
  imports:
    - AstroGlue
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kam-s18/AstroGlue
  summary: AstroGlue serves as a bridge between the AstroLink clustering algorithm and the Glue visualization tool with an interactive GUI for handling various inputs
  license: MIT
  license_family: MIT
  license_file:
    - COPYING.md
    - LICENSE.md
  dev_url: https://github.com/Kam-s18/AstroGlue
  doc_url: https://astroglue.readthedocs.io/

extra:
  recipe-maintainers:
    - Kam-s18
